name: Android CI

on:
  push:
    branches: [ master, develop, alpha ]
  pull_request:
    branches: [ master, develop, alpha ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'

    - uses: gradle/gradle-build-action@v2
      with:
        gradle-home-cache-cleanup: true

    - name: Write key
      run: |
        if [ ! -z "${{ secrets.SIGNING_KEY }}" ]; then
          echo STORE_PASSWORD='${{ secrets.KEY_STORE_PASSWORD }}' >> gradle.properties
          echo KEY_ALIAS='${{ secrets.ALIAS }}' >> gradle.properties
          echo KEY_PASSWORD='${{ secrets.KEY_PASSWORD }}' >> gradle.properties
          echo STORE_FILE_PATH='../release.keystore' >> gradle.properties
          echo ${{ secrets.SIGNING_KEY }} | base64 --decode > release.keystore
          git update-index --assume-unchanged gradle.properties
        fi


    - name: Build with Gradle
      run: ./gradlew assemble

    - name: Collect artifcat name
      run: |
        echo "debug_artifact=$(basename -s .apk app/build/outputs/apk/debug/*.apk)" >> $GITHUB_ENV
        echo "release_artifact=$(basename -s .apk app/build/outputs/apk/release/*.apk)" >> $GITHUB_ENV

    - name: Upload Debug
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.debug_artifact }}
        path: app/build/outputs/apk/debug/*.apk

    - name: Upload Release
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.release_artifact }}
        path: app/build/outputs/apk/release/*.apk