name: Release CI

on:
  push:
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Force fetch Tags
      run: |
        git fetch --tags --force

    - name: Get Tag
      id: var
      run: |
        echo ::set-output name=tag::${GITHUB_REF#refs/*/}
        echo ::set-output name=version::${GITHUB_REF#refs/*/v}

    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'

    - uses: gradle/gradle-build-action@v2
      with:
        gradle-home-cache-cleanup: true

    - name: Write key
      run: |
        if [ ! -z "${{ secrets.SIGNING_KEY }}" ]; then
          echo STORE_PASSWORD='${{ secrets.KEY_STORE_PASSWORD }}' >> gradle.properties
          echo KEY_ALIAS='${{ secrets.ALIAS }}' >> gradle.properties
          echo KEY_PASSWORD='${{ secrets.KEY_PASSWORD }}' >> gradle.properties
          echo STORE_FILE_PATH='../release.keystore' >> gradle.properties
          echo ${{ secrets.SIGNING_KEY }} | base64 --decode > release.keystore
          git update-index --assume-unchanged gradle.properties
        fi

    - name: Build with Gradle
      run: ./gradlew assembleRelease

    - name: Collect artifcat name
      run: |
        echo "release_artifact=$(basename -s .apk app/build/outputs/apk/release/*.apk)" >> $GITHUB_ENV

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.release_artifact }}
        path: app/build/outputs/apk/release/*.apk

    - uses: ericcornelissen/git-tag-annotation-action@v2
      id: tag-data

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        body: ${{ steps.tag-data.outputs.git-tag-annotation }} &#x20;
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Upload APK
      uses: csexton/release-asset-action@v2
      with:
        github-token: ${{ secrets.GH_TOKEN }}
        release-url: ${{ steps.create_release.outputs.upload_url }}
        files: |
          app/build/outputs/mapping/release/mapping.txt
        pattern: "app/build/outputs/apk/release/*.apk"

    - name: Release to XPosed Repo
      id: create_xposed_release
      uses: actions/create-release@v1
      with:
        owner: Xposed-Modules-Repo
        repo: one.yufz.hmspush
        tag_name: ${{ steps.var.outputs.version }}
        release_name: ${{ github.ref }}
        commitish: 301297d3142baf38abc7b5f9a6077f440a3f8392
        body: ${{ steps.tag-data.outputs.git-tag-annotation }} &#x20;
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Upload APK
      uses: csexton/release-asset-action@v2
      with:
        github-token: ${{ secrets.GH_TOKEN }}
        release-url: ${{ steps.create_xposed_release.outputs.upload_url }}
        pattern: "app/build/outputs/apk/release/*.apk"
